version: '3.8'

services:
  students-mongo:
    container_name: ${MONGO_CONTAINER}
    image: mongo:${MONGO_TAG}
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    env_file: .env
    volumes:
      - students-mongo:/data/db

  students-node:
    container_name: students-node
    image: node:${NODE_TAG}
    depends_on:
      - students-mongo
    env_file: .env
    build:
      context: .
      args:
        - NODE_TAG=${NODE_TAG}
    command: sh -c 'pnpm i && pnpm dev -o'
    ports:
      - 3000:${NODE_PORT}
      - 430:${NODE_SSL_PORT}
      - 24678:24678 # nuxt
    volumes:
      - ./:/nuxt

volumes:
  students-mongo:
