version: '3.8'

services:
  students-mongo:
    container_name: ${MONGO_CONTAINER}
    image: mongo:${MONGO_TAG}
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - students-mongo:/data/db

  students-node:
    container_name: students-node
    image: node:${NODE_TAG}
    depends_on:
      - students-mongo
    env_file: .env
    build:
      context: .
      args:
        - NODE_TAG=${NODE_TAG}
    command: sh -c 'pnpm i && pnpm dev -o'
    ports:
      - 3000:${NODE_PORT}
      - 430:${NODE_SSL_PORT}
      - 3001:3001 # vite
    volumes:
      - ./:/nuxt

volumes:
  students-mongo:
